name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  APP_NAME: ${{values.name}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
         username: \$\{{ secrets.DOCKER_USERNAME }}
         password: \$\{{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{values.dockerRepo}}/${{values.name}}:latest -f Dockerfile .

      # Step 4: Push Docker Image to Registry
      - name: Push Docker Image
        run: |
          docker push ${{values.dockerRepo}}/${{values.name}}:latest

      # Step 5: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.DOCKER_KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      # Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        env:
          IMAGE: ${{values.dockerRepo}}/${{values.name}}:latest
        run: |
          kubectl apply -f k8s/deployment.yaml

          # Verify deployment
          kubectl rollout status deployment/${{values.name}}
